#!/usr/bin/env swipl --quiet

:- initialization main.


main :-
  [finances],
  Salary = 37440,
  RentAsAPercentageOfPostTax = 0.60,
  RetirementAsAPercentageOfPreTax = 0.06,
  Groceries = 400,
  Utilities = 150,
  % GroceriesAsAPercentageOfPostTax = 0.10,
  % UtilitiesAsAPercentageOfPostTax = 0.02,
  % TimeToEmergencyFund = 6,
  CurrentBalance = 11000,
  budget(
      Salary, PostTaxSalary,
      Taxes, MonthlyTaxes,
      Rent, RentAsAPercentageOfPostTax,
      Retirement, RetirementAsAPercentageOfPreTax,
      Groceries, GroceriesAsAPercentageOfPostTax,
      Utilities, UtilitiesAsAPercentageOfPostTax,
      TakeHome,
      MonthlyExpenses,
      CurrentBalance,
      EmergencyFund, TimeToEmergencyFund),
  write("Salary: "), write(Salary), nl,
  write("PostTaxSalary: "), write(PostTaxSalary), nl,
  write("Taxes: "), write(Taxes), nl,
  write("MonthlyTaxes: "), write(MonthlyTaxes), nl,
  write("Rent: "), write(Rent), nl,
  write("RentAsAPercentageOfPostTax: "), write(RentAsAPercentageOfPostTax), nl,
  write("Retirement: "), write(Retirement), nl,
  write("RetirementAsAPercentageOfPreTax: "), write(RetirementAsAPercentageOfPreTax), nl,
  write("Groceries: "), write(Groceries), nl,
  write("GroceriesAsAPercentageOfPostTax: "), write(GroceriesAsAPercentageOfPostTax), nl,
  write("Utilities: "), write(Utilities), nl,
  write("UtilitiesAsAPercentageOfPostTax: "), write(UtilitiesAsAPercentageOfPostTax), nl,
  write("TakeHome: "), write(TakeHome), nl,
  write("MonthlyExpenses: "), write(MonthlyExpenses), nl,
  write("CurrentBalance: "), write(CurrentBalance), nl,
  write("EmergencyFund: "), write(EmergencyFund), nl,
  write("TimeToEmergencyFund: "), write(TimeToEmergencyFund), nl,
  halt.
