#!/usr/bin/env swipl --quiet

:- initialization main.


main :-
  [finances],
  Salary = 120000,
  Loans = 126000,
  Rate = 0.048, Term = 10,
  HomeValue = 600000, MortgageRate = 0.06375, MortgageTerm = 30,
  RetirementAsAPercentageOfPreTax = 0.09,
  Lifestyle = 1022,
  HOA = 500,
  % GroceriesAsAPercentageOfPostTax = 0.10,
  UtilitiesAsAPercentageOfPostTax = 0.02,
  % TimeToEmergencyFund = 6,
  CurrentBalance = 26000,
  budget_own(
      Salary, PostTaxSalary,
      Taxes, Federal, California, MonthlyTaxes,
      Loans, MonthlyPayment, Rate, LoansAsAPercentageOfPostTax, Term,
      Mortgage, MortgageRate, MortgageTerm, HomeValue, MortgageAsAPercentageOfPostTax, HOA,
      Retirement, MonthlyRetirement, RetirementAsAPercentageOfPreTax,
      Lifestyle, LifestyleAsAPercentageOfPostTax,
      Utilities, UtilitiesAsAPercentageOfPostTax,
      TakeHome,
      MonthlyExpenses,
      CurrentBalance,
      EmergencyFund, TimeToEmergencyFund),

    SECTION_SEPARATOR = "~`-t~40+|~n",
    ROW_SEPARATOR = "~a~t~40+| ~t~a~t~8+~n",

    nl, write("Salary"), nl,
    format(SECTION_SEPARATOR),
    format(ROW_SEPARATOR, ["Salary", Salary]),
    format(ROW_SEPARATOR, ["Monthly Taxes", MonthlyTaxes]),
    format(ROW_SEPARATOR, ["Annual Taxes", Taxes]),
    format(ROW_SEPARATOR, ["Post-Tax Salary", PostTaxSalary]),
    format(ROW_SEPARATOR, ["Federal Taxes", Federal]),
    format(ROW_SEPARATOR, ["California Taxes", California]),


    format(SECTION_SEPARATOR), nl,
    write("Student Loans"), nl,
    {SLR = Rate * 100},
    {LPT = LoansAsAPercentageOfPostTax * 100},
    format(SECTION_SEPARATOR),
    format(ROW_SEPARATOR, ["Student Loans", Loans]),
    format(ROW_SEPARATOR, ["Weighted Average Rate", SLR]),
    format(ROW_SEPARATOR, ["Years to Loan Repayment", Term]),
    format(ROW_SEPARATOR, ["Monthly Loan Payment", MonthlyPayment]),
    format(ROW_SEPARATOR, ["Loans as a Percentage of Post-Tax", LPT]),

    format(SECTION_SEPARATOR), nl,
    write("Retirement"), nl,
    {RPT = RetirementAsAPercentageOfPreTax * 100},
    format(SECTION_SEPARATOR),
    format(ROW_SEPARATOR, ["Annual Retirment Contributions", Retirement]),
    format(ROW_SEPARATOR, ["Monthly Retirment Contributions", MonthlyRetirement]),
    format(ROW_SEPARATOR, ["Retirment as a Percentage of Pre-Tax", RPT]),

    format(SECTION_SEPARATOR), nl,
    write("Housing"), nl,
    {MR = MortgageRate * 100},
    {MPPT = MortgageAsAPercentageOfPostTax * 100},
    {UPT = UtilitiesAsAPercentageOfPostTax * 100},
    format(SECTION_SEPARATOR),
    format(ROW_SEPARATOR, ["Home Value", HomeValue]),
    format(ROW_SEPARATOR, ["Mortgage Rate", MR]),
    format(ROW_SEPARATOR, ["Mortgage Term", MortgageTerm]),
    format(ROW_SEPARATOR, ["Monthly Mortgage", Mortgage]),
    format(ROW_SEPARATOR, ["HOA Fees", HOA]),
    format(ROW_SEPARATOR, ["Mortage as a % of Post-Tax", MPPT]),
    format(ROW_SEPARATOR, ["Utilities", Utilities]),
    format(ROW_SEPARATOR, ["Utilities as a Percentage of Post-Tax", UPT]),

    format(SECTION_SEPARATOR), nl,
    write("Expenses and Savings"), nl,
    format(SECTION_SEPARATOR),
    format(ROW_SEPARATOR, ["Monthly Expenses", MonthlyExpenses]),
    format(ROW_SEPARATOR, ["Current Savings Balance", CurrentBalance]),
    format(ROW_SEPARATOR, ["Target Six Month Emergency Fund", EmergencyFund]),
    format(ROW_SEPARATOR, ["Months to Emergency Fund", TimeToEmergencyFund]),

    format(SECTION_SEPARATOR), nl,
    write("Lifestyle"), nl,
    {LSPT = LifestyleAsAPercentageOfPostTax * 100},
    {Allowance = Lifestyle + TakeHome},
    format(SECTION_SEPARATOR),
    format(ROW_SEPARATOR, ["Monthly 'Whatever I want' Allowance", Allowance]),
    format(ROW_SEPARATOR, ["Average Monthly Lifestyle", Lifestyle]),
    format(ROW_SEPARATOR, ["Lifestyle Inflation Allowance", TakeHome]),
    format(ROW_SEPARATOR, ["Lifestyle as a Percentage of Post-Tax", LSPT]),

    format(SECTION_SEPARATOR), nl,
  halt.
