#!/usr/bin/env swipl --quiet

:- initialization main.


main :-
  [finances],
  Salary = 120000,
  Loans = 135000,
  Rate = 0.0428, Term = 10,
  Rent = 2400,
  Retirement = 10000,
  DownPaymentContribution = 0,
  Lifestyle = 1022,
  Utilities = 150,
  CurrentBalance = 24000,
  budget_rent(
      Salary, PostTaxSalary,
      Taxes, MonthlyTaxes,
      Loans, MonthlyPayment, Rate, LoansAsAPercentageOfPostTax, Term,
      Rent, RentAsAPercentageOfPostTax,
      Retirement, MonthlyRetirement, RetirementAsAPercentageOfPreTax,
      DownPaymentContribution, MonthlyDownPaymentContribution, DownPaymentContributionAsAPercentageOfPostTax,
      Lifestyle, LifestyleAsAPercentageOfPostTax,
      Utilities, UtilitiesAsAPercentageOfPostTax,
      TakeHome,
      MonthlyExpenses,
      CurrentBalance,
      EmergencyFund, TimeToEmergencyFund),

  SECTION_SEPARATOR = "~`-t~40+|~n",
  ROW_SEPARATOR = "~a~t~40+| ~t~a~t~8+~n",

  nl, write("Salary"), nl,
  format(SECTION_SEPARATOR),
  format(ROW_SEPARATOR, ["Salary", Salary]),
  format(ROW_SEPARATOR, ["Monthly Taxes", MonthlyTaxes]),
  format(ROW_SEPARATOR, ["Annual Taxes", Taxes]),
  format(ROW_SEPARATOR, ["Post-Tax Salary", PostTaxSalary]),

  format(SECTION_SEPARATOR), nl,
  write("Student Loans"), nl,
  {SLR = Rate * 100},
  {LPT = LoansAsAPercentageOfPostTax * 100},
  format(SECTION_SEPARATOR),
  format(ROW_SEPARATOR, ["Student Loans", Loans]),
  format(ROW_SEPARATOR, ["Weighted Average Rate", SLR]),
  format(ROW_SEPARATOR, ["Years to Loan Repayment", Term]),
  format(ROW_SEPARATOR, ["Monthly Loan Payment", MonthlyPayment]),
  format(ROW_SEPARATOR, ["Loans as a Percentage of Post-Tax", LPT]),

  format(SECTION_SEPARATOR), nl,
  write("Retirement"), nl,
  {RPT = RetirementAsAPercentageOfPreTax * 100},
  format(SECTION_SEPARATOR),
  format(ROW_SEPARATOR, ["Annual Retirment Contributions", Retirement]),
  format(ROW_SEPARATOR, ["Monthly Retirment Contributions", MonthlyRetirement]),
  format(ROW_SEPARATOR, ["Retirment as a Percentage of Pre-Tax", RPT]),

  format(SECTION_SEPARATOR), nl,
  write("Housing"), nl,
  {RentPT = RentAsAPercentageOfPostTax * 100},
  {UPT = UtilitiesAsAPercentageOfPostTax * 100},
  format(SECTION_SEPARATOR),
  format(ROW_SEPARATOR, ["Monthly Rent", Rent]),
  format(ROW_SEPARATOR, ["Rent as a Percentage of Post-Tax", RentPT]),
  format(ROW_SEPARATOR, ["Utilities", Utilities]),
  format(ROW_SEPARATOR, ["Utilities as a Percentage of Post-Tax", UPT]),

  format(SECTION_SEPARATOR), nl,
  write("Home Ownership"), nl,
  {DPPT = DownPaymentContributionAsAPercentageOfPostTax * 100},
  format(SECTION_SEPARATOR),
  format(ROW_SEPARATOR, ["Annual Down Payment Contribution", DownPaymentContribution]),
  format(ROW_SEPARATOR, ["Monthly Home Down Payment Contribution", MonthlyDownPaymentContribution]),
  format(ROW_SEPARATOR, ["Down Payment as a Percentage of Post-Tax", DPPT]),

  format(SECTION_SEPARATOR), nl,
  write("Expenses and Savings"), nl,
  format(SECTION_SEPARATOR),
  format(ROW_SEPARATOR, ["Monthly Expenses", MonthlyExpenses]),
  format(ROW_SEPARATOR, ["Current Savings Balance", CurrentBalance]),
  format(ROW_SEPARATOR, ["Target Six Month Emergency Fund", EmergencyFund]),
  format(ROW_SEPARATOR, ["Months to Emergency Fund", TimeToEmergencyFund]),

  format(SECTION_SEPARATOR), nl,
  write("Lifestyle"), nl,
  {LSPT = LifestyleAsAPercentageOfPostTax * 100},
  {Allowance = Lifestyle + TakeHome},
  format(SECTION_SEPARATOR),
  format(ROW_SEPARATOR, ["Monthly 'Whatever I want' Allowance", Allowance]),
  format(ROW_SEPARATOR, ["Average Monthly Lifestyle", Lifestyle]),
  format(ROW_SEPARATOR, ["Lifestyle Inflation Allowance", TakeHome]),
  format(ROW_SEPARATOR, ["Lifestyle as a Percentage of Post-Tax", LSPT]),

  format(SECTION_SEPARATOR), nl,
  halt.
